stages:
  - prepare
  - build
  - deploy

image: docker:${DOCKER_VERSION}
variables:
  DOCKER_BUILDKIT: 1
  DOCKER_VERSION: 20.10.17

.docker_init_template:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

.ssh_init_template:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa

install:
  stage: prepare
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--registry-mirror", "https://registry-proxy.x5.money"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p node_modules

    - >
      docker build
      --file docker/node/Dockerfile
      --target install
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
      .

    - rm -rf node_modules

    - docker create --name node $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
    - docker cp node:/app/node_modules $CI_PROJECT_DIR/

.build_production_template:
  stage: build
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--registry-mirror", "https://registry-proxy.x5.money"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull
    - key: next-cache-${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
      paths:
        - .next/cache
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p .next/cache

    - >
      docker build
      --file docker/node/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --target builder
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --build-arg NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
      --build-arg NEXT_PUBLIC_DATA_POLICY=$NEXT_PUBLIC_DATA_POLICY
      --build-arg NEXT_PUBLIC_TARIFFS=$NEXT_PUBLIC_TARIFFS
      --build-arg NEXT_PUBLIC_USER_AGREEMENT=$NEXT_PUBLIC_USER_AGREEMENT
      --build-arg NEXT_PUBLIC_BOT_LINK=$NEXT_PUBLIC_BOT_LINK
      --build-arg NEXT_PUBLIC_TEXT_SECOND_CHECKBOX="$NEXT_PUBLIC_TEXT_SECOND_CHECKBOX"
      --build-arg NEXT_PUBLIC_COMPANY_NAME="$NEXT_PUBLIC_COMPANY_NAME"
      --build-arg NEXT_PUBLIC_COMPANY_INN=$NEXT_PUBLIC_COMPANY_INN
      --build-arg NEXT_PUBLIC_COMPANY_OGRNIP=$NEXT_PUBLIC_COMPANY_OGRNIP
      .

    - rm -rf .next/cache

    - docker create --name main_page $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    - docker cp main_page:/app/.next/cache $CI_PROJECT_DIR/.next/cache

    - docker push $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

.deploy_production_template:
  stage: deploy
  environment:
    name: production-${PROJECT_NAME}
  variables:
    COMPOSE_PROJECT_NAME: ${PROJECT_NAME}_main_page
    LANDING_IMAGE: $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    DOCKER_HOST: $DEPLOY_PROD_DOCKER_HOST
  before_script:
    - !reference [.ssh_init_template]
    - !reference [.docker_init_template]
  script:
    - docker compose pull  frontend

    - docker compose up -d --wait
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build_lovebotclick:
  extends: .build_production_template
  variables:
    PROJECT_NAME: lovebotclick
    NEXT_PUBLIC_BACKEND_URL: https://api.lovebot.pro
    NEXT_PUBLIC_DATA_POLICY: https://docs.google.com/document/d/11ntwB7fqvLM1RYB1-W0y4046AkH3e8qhNb3qyWWETo8/edit?usp=sharing
    NEXT_PUBLIC_TARIFFS: https://cdn-lovebot.x5.money/tariffs.pdf
    NEXT_PUBLIC_USER_AGREEMENT: https://docs.google.com/document/d/1wUCaCHZGo42OHUtUZcL2e1y80lrDDIext-Qs7N5UFZw/edit?usp=sharing
    NEXT_PUBLIC_BOT_LINK: https://vk.me/public219803842
    NEXT_PUBLIC_TEXT_SECOND_CHECKBOX: Нажимая кнопку “Оплатить” Вы оплачиваете 29₽ и подтверждаете ознакомление с автоматическими списаниями. Через 24 часа, будет совершено автоматическое продление за 889 р. на 3 дня, либо 589 руб. на 2 дня или 289 руб. за 1 день.
    NEXT_PUBLIC_COMPANY_NAME: ИП Рякин Егор Андреевич
    NEXT_PUBLIC_COMPANY_INN: 471910121614
    NEXT_PUBLIC_COMPANY_OGRNIP: 323470400012068

deploy_production_lovebotclick:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: lovebotclick
    VIRTUAL_HOST: lovebot.click